apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gj249spvu-go
  janus-idp.io/tekton: gj249spvu-go
  backstage.io/kubernetes-id: gj249spvu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gj249spvu-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
